#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u 'Henrique1792' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"


"creating git repository if it doesn't exist"
git init
git remote add origin "https://github.com/Henrique1792/$repo_name.git"
